In [1]:
import numpy as np

# Define the input tensor
tensor = np.random.rand(28, 28, 3)

# Define the conversion matrix
matrix = np.array([[17.8824, 43.5161, 4.11953],
                   [3.45565, 27.1554, 3.86714],
                   [0.0299566, 0.184309, 1.46709]])

In [2]:
# Reshape the tensor to a 2D array with shape (28*28, 3)
tensor_reshaped = tensor.reshape((28*28, 3))

# Multiply the reshaped tensor with the matrix
output_reshaped = np.dot(tensor_reshaped, matrix.T)

# Reshape the output to the original tensor shape
output = output_reshaped.reshape((28, 28, 3))

# Print the output
print(output)

[[[1.96540364e+01 6.68459810e+00 1.14425797e+00]
  [2.58670404e+01 1.57169681e+01 1.17396959e+00]
  [3.82293925e+01 2.01315487e+01 6.17435635e-01]
  ...
  [4.03918723e+01 2.51215554e+01 4.50384363e-01]
  [5.75489634e+01 3.10885413e+01 8.36198901e-01]
  [3.29538975e+01 2.11526692e+01 1.49685842e+00]]

 [[4.06702607e+01 1.92831085e+01 6.00477602e-01]
  [4.20629361e+01 2.40645055e+01 7.16838785e-01]
  [4.65182281e+01 2.64863661e+01 6.54596804e-01]
  ...
  [1.83938040e+01 6.21014656e+00 2.15000122e-01]
  [2.25006210e+01 9.51795723e+00 2.67872531e-01]
  [2.90279522e+01 1.86062191e+01 9.45110578e-01]]

 [[2.10310484e+01 1.11500146e+01 3.35233009e-01]
  [5.10563116e+01 2.72432587e+01 8.45731939e-01]
  [2.65539019e+01 1.02440579e+01 2.09849587e-01]
  ...
  [1.81572680e+01 1.00608286e+01 6.41851379e-01]
  [4.81265847e+01 2.83069016e+01 7.90041421e-01]
  [4.30321895e+01 2.11284987e+01 8.08804435e-01]]

 ...

 [[3.90899639e+01 1.93953824e+01 4.23223873e-01]
  [1.51653562e+01 8.83068344e+00 1.2276

In [4]:
r = np.array([3,5,3,2,3,5,9,8,7])

In [21]:
g = []
gama = 0.7
for i in range(len(r)):
    ret = 0
    for j in range(i, len(r)):
        if i == (len(r) - 1) or i in [0, 1]:
            print(f"{gama}^{j-i} x {r[j]}")
        ret += (r[j] * (gama**(j-i)))

    print("")

    g.append(ret)

0.7^0 x 3
0.7^1 x 5
0.7^2 x 3
0.7^3 x 2
0.7^4 x 3
0.7^5 x 5
0.7^6 x 9
0.7^7 x 8
0.7^8 x 7

0.7^0 x 5
0.7^1 x 3
0.7^2 x 2
0.7^3 x 3
0.7^4 x 5
0.7^5 x 9
0.7^6 x 8
0.7^7 x 7







0.7^0 x 7



In [22]:
g

[12.337861469999996,
 13.339802099999998,
 11.914002999999997,
 12.734289999999998,
 15.3347,
 17.621,
 18.03,
 12.899999999999999,
 7.0]

In [25]:
gama = 0.7
rewards = r
returns = []
rewards_r = rewards[::-1]
returns.append(rewards_r[0])
for i in range(1, len(rewards_r)):
    returns.append(rewards_r[i] + (gama * returns[-1]))

returns = returns[::-1]

In [23]:
g = []
gama = 0.7
r_r = r[::-1]
g.append(r_r[0])
for i in range(1, len(r_r)):
    g.append(r_r[i] + (gama * g[-1]))

g = g[::-1]

In [24]:
g

[12.337861469999998,
 13.339802099999998,
 11.914002999999997,
 12.734289999999996,
 15.334699999999996,
 17.620999999999995,
 18.029999999999998,
 12.899999999999999,
 7]